kind: pipeline
name: default
steps:
  - name: build app DEV
    image: plugins/docker
    settings:
      repo: ankrnetwork/${DRONE_REPO_NAME}
      tags: [ "${DRONE_COMMIT_SHA:0:7}", "latest" ]
      username:
        from_secret: registry_user
      password:
        from_secret: registry_passwd
    when:
      event:
        - push
      branch:
        - develop

  - name: Deploy app DEV
    image: appleboy/drone-ssh:1.6.6-linux-amd64
    settings:
      host:
        - 52.53.250.208
      username: root
      key:
        from_secret: ape_mategame_dev
      port: 22
      command_timeout: 2m
      script:
        - docker stop ${DRONE_REPO_NAME}
        - docker rm ${DRONE_REPO_NAME}
        - docker run --pull always -d --name ${DRONE_REPO_NAME} -v /home/ankr/Ankr-network/bridge-backend/:/go/src/etc/  -p 7999:7999 ankrnetwork/${DRONE_REPO_NAME}:latest
    when:
      event:
        - push
      branch:
        - develop

  - name: build app PROD
    image: plugins/docker
    settings:
      registry: hub.docker.com
      repo: hub.docker.com/ankrnetwork/${DRONE_REPO_NAME}
      tags: ["${DRONE_COMMIT_SHA:0:7}", "release"]
      username:
        from_secret: registry_user
      password:
        from_secret: registry_passwd
    when:
      event:
        - push
      branch:
        - main

  - name: deploy app PROD
    image: danielgormly/drone-plugin-kube:0.1.0
    settings:
      template: ./k8.yaml
      ca:
        from_secret: kubernetes_ca
      server:
        from_secret: kubernetes_server
      token:
        from_secret: kubernetes_token
    when:
      event:
        - push
      branch:
        - main