Debug: true
Listen: 0.0.0.0:7999
DB:
  Driver: mysql
  Source: ape_admin:ape_admin@tcp(172.31.19.28:3306)/bridge_service?charset=utf8mb4&parseTime=True&loc=Local
  Debug:  true
EtcdEndpoints:
  - "http://127.0.0.1:2379"
Valut:
  Endpoint: https://vault-dev.ankr.com
  Role: 41524d66-95b0-9523-136e-fd24ee9fcac2
  Secret: 78595c1f-08d4-f6df-ab38-4fc97471c0ea
ChainCfg:
  - RpcUrl: http://103.23.44.17:18575
    Graph: http://103.23.44.17:18575/graphql
    BlockStep: 5
    BlockDelay: 13
    NetworkId: 97
    AdminAddress: 0xd6a5914E2b8676bD8Fd2fcD9c0fD1FCf1B5A9411
    BridgeContract721: 0x03CBcAa350A7f35E7D60976c9ee9AdC5ed46BF23
  - RpcUrl: https://testnet.ankr.com
    Graph: https://testnet.ankr.com/graphql
    BlockStep: 5
    BlockDelay: 13
    NetworkId: 12077
    AdminAddress: 0xd6a5914E2b8676bD8Fd2fcD9c0fD1FCf1B5A9411
    BridgeContract721: 0x03A84dAabd08BC7C765222d0930173395AEe4F9f
    BridgeContract20: 0x6cd0F422E0E022E7180E04Aea3121a0793d7cF6F
  - RpcUrl: https://meta-ape-edge-testnet-01.ankr.com
    BlockStep: 5
    BlockDelay: 13
    NetworkId: 100
    AdminAddress: 0xd6a5914E2b8676bD8Fd2fcD9c0fD1FCf1B5A9411
    BridgeContract721: 0x228b4F12eE49F22528270eF47a27261d294557b5
  - RpcUrl: https://bas-testnet.ankr.com
    Graph: https://bas-testnet.ankr.com/graphql
    BlockStep: 5
    BlockDelay: 13
    NetworkId: 15001
    AdminAddress: 0xd6a5914E2b8676bD8Fd2fcD9c0fD1FCf1B5A9411
    BridgeContract721: 0xDBC0CB3907D05639B563be3d87E9bC2C52A5FC10


